name: 'a-okvqa'
type: 'gen'
module: "tasks.vqa.task.VQAGenTask"
path: 'aokvqa_v1p0'
file-pattern:
  validation: "aokvqa_v1p0_val.json"
clip-pattern:
  train: "/zhangpai21/workspace/zxdu/VQA/aokvqa_clip_train.jsonl"
  validation: "/zhangpai21/workspace/zxdu/VQA/aokvqa_clip_val.jsonl"
  test: "/zhangpai21/workspace/zxdu/VQA/aokvqa_clip_test.jsonl"
caption-pattern:
  train: "/zhangpai21/workspace/zxdu/VQA/aokvqa_blip_train.jsonl"
  validation: "/zhangpai21/workspace/zxdu/VQA/aokvqa_blip_val.jsonl"
  test: "/zhangpai21/workspace/zxdu/VQA/aokvqa_blip_test.jsonl"
sampling_strategy: "BeamSearchStrategy"
num_beams: 4
max_gen_length: 8
save_prediction: true
priming: true
end_tokens: ["."]
num_train_examples: 10
train_path: "/zhangpai21/workspace/zxdu/aokvqa_v1p0/aokvqa_v1p0_train.json"